# Generated by Django 5.2.4 on 2025-07-31 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('work', 'Travail'), ('personal', 'Personnel'), ('urgent', 'Urgent'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Catégorie')),
                ('status', models.CharField(choices=[('todo', 'À faire'), ('in_progress', 'En cours'), ('completed', 'Terminé')], default='todo', max_length=20, verbose_name='Statut')),
                ('priority', models.IntegerField(default=1, help_text='1=Basse, 2=Moyenne, 3=Haute', verbose_name='Priorité')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Élément',
                'verbose_name_plural': 'Éléments',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du service')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('code', models.CharField(help_text='Code unique pour identifier le service (ex: DRH, COMPTA)', max_length=20, unique=True, verbose_name='Code du service')),
                ('responsable', models.CharField(blank=True, help_text='Nom du responsable du service', max_length=100, verbose_name='Responsable')),
                ('email_contact', models.EmailField(blank=True, max_length=254, verbose_name='Email de contact')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('actif', models.BooleanField(default=True, verbose_name='Service actif')),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Pour organiser l'ordre d'affichage dans l'organigramme", verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_services', to='core.service', verbose_name='Service parent')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['ordre', 'nom'],
            },
        ),
    ]
