# Generated by Django 5.2.4 on 2025-07-31 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['nom'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='email_contact',
        ),
        migrations.RemoveField(
            model_name='service',
            name='ordre',
        ),
        migrations.RemoveField(
            model_name='service',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='service',
            name='telephone',
        ),
    ]
