# Generated by Django 5.2.4 on 2025-08-02 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auditsource_department_process_gapreport_gaptype_gap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gapreport',
            name='department',
        ),
        migrations.AddField(
            model_name='gapreport',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.service', verbose_name='Service concerné'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
