# Generated by Django 5.2.4 on 2025-07-31 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_service_options_remove_service_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='actif',
        ),
    ]
