# Generated by Django 5.2.4 on 2025-08-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_gapreport_department_gapreport_service_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gapreport',
            options={'ordering': ['-observation_date', '-created_at'], 'verbose_name': "3. Déclaration d'écart", 'verbose_name_plural': "3. Déclarations d'évenements"},
        ),
        migrations.AlterField(
            model_name='gapreport',
            name='observation_date',
            field=models.DateTimeField(verbose_name="Date et heure d'observation"),
        ),
    ]
