# Generated by Django 5.2.4 on 2025-08-02 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_change_observation_date_to_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditsource',
            options={'ordering': ['name'], 'verbose_name': "3.1 Source d'audit", 'verbose_name_plural': "3.1 Sources d'audit"},
        ),
        migrations.RemoveField(
            model_name='auditsource',
            name='is_active',
        ),
    ]
