# Generated by Django 5.2.4 on 2025-08-02 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_audit_source_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditsource',
            name='code',
        ),
    ]
