# Generated by Django 5.2.4 on 2025-08-03 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_audit_source_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gaptype',
            options={'ordering': ['audit_source__name', 'name'], 'verbose_name': "3.3 Type d'évenements", 'verbose_name_plural': "3.3 Types d'écart"},
        ),
        migrations.AlterModelOptions(
            name='process',
            options={'ordering': ['name'], 'verbose_name': '3.2 Processus SMI', 'verbose_name_plural': '3.2 Processus SMI'},
        ),
        migrations.AlterUniqueTogether(
            name='gaptype',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='gaptype',
            name='code',
        ),
        migrations.RemoveField(
            model_name='gaptype',
            name='is_active',
        ),
    ]
