# Generated by Django 5.2.4 on 2025-08-03 02:44

import core.models.attachments
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_gaptype_options_alter_process_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GapAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(help_text='Nom descriptif de la pièce jointe', max_length=200, verbose_name='Nom de la pièce jointe')),
                ('file', models.FileField(upload_to=core.models.attachments.gap_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'jpg', 'jpeg', 'png', 'gif', 'txt', 'csv'])], verbose_name='Fichier')),
                ('gap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.gap', verbose_name='Écart')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name': "Pièce jointe d'écart",
                'verbose_name_plural': "Pièces jointes d'écart",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GapReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(help_text='Nom descriptif de la pièce jointe', max_length=200, verbose_name='Nom de la pièce jointe')),
                ('file', models.FileField(upload_to=core.models.attachments.gap_report_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'jpg', 'jpeg', 'png', 'gif', 'txt', 'csv'])], verbose_name='Fichier')),
                ('gap_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.gapreport', verbose_name="Déclaration d'écart")),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name': 'Pièce jointe de déclaration',
                'verbose_name_plural': 'Pièces jointes de déclaration',
                'ordering': ['-created_at'],
            },
        ),
    ]
