# Generated by Django 5.2.4 on 2025-08-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_gapattachment_gapreportattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gap',
            name='status',
            field=models.CharField(choices=[('declared', 'Déclaré'), ('cancelled', 'Annulé'), ('retained', 'Retenu'), ('rejected', 'Non retenu'), ('closed', 'Clos')], default='declared', max_length=20, verbose_name='Statut'),
        ),
    ]
