# Generated by Django 5.2.4 on 2025-08-04 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_gap_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('action', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('changement_statut', 'Changement de statut')], max_length=20, verbose_name='Action')),
                ('objet_type', models.CharField(choices=[('gap_report', "Déclaration d'écart"), ('gap', 'Écart')], max_length=20, verbose_name="Type d'objet")),
                ('objet_id', models.PositiveIntegerField(verbose_name="ID de l'objet")),
                ('objet_repr', models.CharField(help_text="Représentation textuelle de l'objet au moment de la modification", max_length=200, verbose_name="Représentation de l'objet")),
                ('description', models.TextField(help_text='Description détaillée des changements effectués', verbose_name='Description de la modification')),
                ('donnees_avant', models.JSONField(blank=True, help_text='État des données avant la modification (format JSON)', null=True, verbose_name='Données avant modification')),
                ('donnees_apres', models.JSONField(blank=True, help_text='État des données après la modification (format JSON)', null=True, verbose_name='Données après modification')),
                ('gap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique_modifications', to='core.gap', verbose_name='Écart')),
                ('gap_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique_modifications', to='core.gapreport', verbose_name="Déclaration d'écart")),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Historique de modification',
                'verbose_name_plural': 'Historiques de modifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gap_report', '-created_at'], name='core_histor_gap_rep_24974f_idx'), models.Index(fields=['gap', '-created_at'], name='core_histor_gap_id_e56e97_idx'), models.Index(fields=['objet_type', 'objet_id', '-created_at'], name='core_histor_objet_t_52d971_idx')],
            },
        ),
    ]
