# Generated by Django 5.2.4 on 2025-08-06 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_historiquemodification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gap',
            options={'ordering': ['-created_at'], 'verbose_name': '3.4 Écart', 'verbose_name_plural': '3.4 Écarts'},
        ),
        migrations.AlterModelOptions(
            name='gapattachment',
            options={'ordering': ['-created_at'], 'verbose_name': "3.6 Pièce jointe d'écart", 'verbose_name_plural': "3.6 Pièces jointes d'écart"},
        ),
        migrations.AlterModelOptions(
            name='gapreportattachment',
            options={'ordering': ['-created_at'], 'verbose_name': '3.5 Pièce jointe de déclaration', 'verbose_name_plural': '3.5 Pièces jointes de déclaration'},
        ),
        migrations.AlterModelOptions(
            name='gaptype',
            options={'ordering': ['audit_source__name', 'name'], 'verbose_name': "3.3 Type d'événement", 'verbose_name_plural': "3.3 Types d'événement"},
        ),
        migrations.AddField(
            model_name='gaptype',
            name='is_gap',
            field=models.BooleanField(default=True, help_text='Cochez si cet événement constitue un écart. Décochez pour un simple événement.', verbose_name='Écart'),
        ),
        migrations.AlterField(
            model_name='gap',
            name='gap_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.gaptype', verbose_name="Type d'événement (Quoi)"),
        ),
        migrations.AlterField(
            model_name='gaptype',
            name='name',
            field=models.CharField(max_length=100, verbose_name="Nom du type d'événement"),
        ),
    ]
