# Generated by Django 5.2.4 on 2025-08-07 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_gap_options_alter_gapattachment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidateurService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('niveau', models.IntegerField(choices=[(1, 'Niveau 1'), (2, 'Niveau 2'), (3, 'Niveau 3')], verbose_name='Niveau de validation')),
                ('actif', models.BooleanField(default=True, help_text='Décocher pour désactiver temporairement cette affectation', verbose_name='Actif')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validateurs', to='core.service', verbose_name='Service')),
                ('validateur', models.ForeignKey(limit_choices_to={'droits__in': ['AD', 'SA']}, on_delete=django.db.models.deletion.CASCADE, related_name='services_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validateur')),
            ],
            options={
                'verbose_name': 'Validateur de service',
                'verbose_name_plural': 'Validateurs de service',
                'ordering': ['service__nom', 'niveau'],
                'unique_together': {('service', 'validateur', 'niveau')},
            },
        ),
    ]
