# Generated by Django 5.2.4 on 2025-08-08 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_validateurservice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='validateurservice',
            unique_together={('service', 'niveau')},
        ),
    ]
