# Generated by Django 5.2.4 on 2025-08-08 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_validateurservice_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validateurservice',
            name='validateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validateur'),
        ),
    ]
