# Generated by Django 5.2.4 on 2025-08-08 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_validateurservice_validateur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validateurservice',
            options={'ordering': ['service__nom', 'audit_source__name', 'niveau'], 'verbose_name': 'Validateur de service', 'verbose_name_plural': 'Validateurs de service'},
        ),
        migrations.AlterUniqueTogether(
            name='validateurservice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='validateurservice',
            name='audit_source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='validateurs', to='core.auditsource', verbose_name="Source d'audit"),
        ),
        migrations.AlterUniqueTogether(
            name='validateurservice',
            unique_together={('service', 'audit_source', 'niveau')},
        ),
    ]
