# Generated by Django 5.2.4 on 2025-08-09 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_validateurservice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validateurservice',
            options={'ordering': ['service__nom', 'audit_source__name', 'niveau'], 'verbose_name': '4. Validateurs', 'verbose_name_plural': '4. Validateurs'},
        ),
        migrations.AddField(
            model_name='service',
            name='actif',
            field=models.BooleanField(default=True, help_text="Un service inactif reste dans l'historique mais n'apparaît plus dans les listes de sélection", verbose_name='Service actif'),
        ),
    ]
