# Generated by Django 5.2.4 on 2025-08-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_service_actif_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='actif',
            field=models.BooleanField(default=True, help_text="Un utilisateur inactif ne peut plus se connecter mais reste dans l'historique", verbose_name='Utilisateur actif'),
        ),
    ]
