# Generated by Django 5.2.4 on 2025-08-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_user_actif_field'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditsource',
            index=models.Index(fields=['name'], name='core_audits_name_c56f46_idx'),
        ),
        migrations.AddIndex(
            model_name='auditsource',
            index=models.Index(fields=['requires_process'], name='core_audits_require_604876_idx'),
        ),
        migrations.AddIndex(
            model_name='gap',
            index=models.Index(fields=['-created_at'], name='core_gap_created_f955aa_idx'),
        ),
        migrations.AddIndex(
            model_name='gap',
            index=models.Index(fields=['gap_report', '-created_at'], name='core_gap_gap_rep_9d7e1b_idx'),
        ),
        migrations.AddIndex(
            model_name='gap',
            index=models.Index(fields=['status', '-created_at'], name='core_gap_status_5fe5c0_idx'),
        ),
        migrations.AddIndex(
            model_name='gap',
            index=models.Index(fields=['gap_type', '-created_at'], name='core_gap_gap_typ_0aed73_idx'),
        ),
        migrations.AddIndex(
            model_name='gap',
            index=models.Index(fields=['gap_number'], name='core_gap_gap_num_54db35_idx'),
        ),
        migrations.AddIndex(
            model_name='gap',
            index=models.Index(fields=['gap_report', 'status'], name='core_gap_gap_rep_feafc6_idx'),
        ),
        migrations.AddIndex(
            model_name='gap',
            index=models.Index(fields=['gap_type', 'status'], name='core_gap_gap_typ_617c80_idx'),
        ),
        migrations.AddIndex(
            model_name='gapreport',
            index=models.Index(fields=['-observation_date', '-created_at'], name='core_gaprep_observa_ea6ff1_idx'),
        ),
        migrations.AddIndex(
            model_name='gapreport',
            index=models.Index(fields=['audit_source', '-observation_date'], name='core_gaprep_audit_s_f3d9dd_idx'),
        ),
        migrations.AddIndex(
            model_name='gapreport',
            index=models.Index(fields=['service', '-observation_date'], name='core_gaprep_service_16e246_idx'),
        ),
        migrations.AddIndex(
            model_name='gapreport',
            index=models.Index(fields=['declared_by', '-observation_date'], name='core_gaprep_declare_2ee245_idx'),
        ),
        migrations.AddIndex(
            model_name='gapreport',
            index=models.Index(fields=['process', '-observation_date'], name='core_gaprep_process_a3cc57_idx'),
        ),
        migrations.AddIndex(
            model_name='gapreport',
            index=models.Index(fields=['audit_source', 'service', '-observation_date'], name='core_gaprep_audit_s_5be04e_idx'),
        ),
        migrations.AddIndex(
            model_name='gaptype',
            index=models.Index(fields=['audit_source', 'name'], name='core_gaptyp_audit_s_b86e95_idx'),
        ),
        migrations.AddIndex(
            model_name='gaptype',
            index=models.Index(fields=['is_gap'], name='core_gaptyp_is_gap_d79f5e_idx'),
        ),
        migrations.AddIndex(
            model_name='gaptype',
            index=models.Index(fields=['audit_source', 'is_gap'], name='core_gaptyp_audit_s_d47c22_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['name'], name='core_proces_name_f4d360_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['code'], name='core_proces_code_8b33ae_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['is_active'], name='core_proces_is_acti_c2eb47_idx'),
        ),
    ]
