# Generated by Django 5.2.4 on 2025-08-10 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GapValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('level', models.IntegerField(verbose_name='Niveau de validation')),
                ('action', models.CharField(choices=[('approved', 'Approuvé'), ('rejected', 'Rejeté')], max_length=10, verbose_name='Action')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('validated_at', models.DateTimeField(auto_now_add=True, verbose_name='Validé le')),
                ('gap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='core.gap', verbose_name='Écart')),
                ('validator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gap_validations', to=settings.AUTH_USER_MODEL, verbose_name='Validateur')),
            ],
            options={
                'verbose_name': "5.1 Validation d'écart",
                'verbose_name_plural': "5.1 Validations d'écarts",
                'ordering': ['-validated_at'],
                'indexes': [models.Index(fields=['gap', 'level'], name='core_gapval_gap_id_8a2ada_idx'), models.Index(fields=['validator', '-validated_at'], name='core_gapval_validat_3551f1_idx'), models.Index(fields=['action', '-validated_at'], name='core_gapval_action_b51297_idx')],
                'unique_together': {('gap', 'level')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('type', models.CharField(choices=[('validation_request', 'Demande de validation'), ('validation_approved', 'Validation approuvée'), ('validation_rejected', 'Validation rejetée'), ('gap_retained', 'Écart retenu'), ('gap_rejected', 'Écart non retenu')], max_length=20, verbose_name='Type de notification')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('normal', 'Normale'), ('high', 'Haute')], default='normal', max_length=10, verbose_name='Priorité')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lu le')),
                ('gap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.gap', verbose_name='Écart concerné')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': '5. Notification',
                'verbose_name_plural': '5. Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_notifi_user_id_1cc5b6_idx'), models.Index(fields=['user', 'is_read', '-created_at'], name='core_notifi_user_id_f286cd_idx'), models.Index(fields=['gap', '-created_at'], name='core_notifi_gap_id_c5b84e_idx'), models.Index(fields=['type', '-created_at'], name='core_notifi_type_28fae6_idx')],
            },
        ),
    ]
