# Generated by Django 5.2.4 on 2025-08-10 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_gapvalidation_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='gap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.gap', verbose_name='Écart concerné'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('validation_request', 'Demande de validation'), ('validation_approved', 'Validation approuvée'), ('validation_rejected', 'Validation rejetée'), ('gap_retained', 'Écart retenu'), ('gap_rejected', 'Écart non retenu'), ('gap_created', 'Écart créé'), ('gap_modified', 'Écart modifié'), ('gap_deleted', 'Écart supprimé')], max_length=20, verbose_name='Type de notification'),
        ),
    ]
