# Generated by Django 5.2.4 on 2025-08-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_notification_gap_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('validation_request', 'Demande de validation'), ('validation_approved', 'Validation approuvée'), ('validation_rejected', 'Validation rejetée'), ('validation_completed', 'Validation effectuée'), ('gap_retained', 'Écart retenu'), ('gap_rejected', 'Écart non retenu'), ('gap_created', 'Écart créé'), ('gap_modified', 'Écart modifié'), ('gap_deleted', 'Écart supprimé')], max_length=20, verbose_name='Type de notification'),
        ),
    ]
