# Generated by Django 5.2.4 on 2025-08-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditsource',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Les sources inactives ne sont plus proposées dans les formulaires mais les données existantes sont préservées', verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='gaptype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Les types inactifs ne sont plus proposés dans les formulaires mais les données existantes sont préservées', verbose_name='Actif'),
        ),
        migrations.AddIndex(
            model_name='auditsource',
            index=models.Index(fields=['is_active'], name='core_audits_is_acti_577979_idx'),
        ),
        migrations.AddIndex(
            model_name='gaptype',
            index=models.Index(fields=['is_active'], name='core_gaptyp_is_acti_d7f7cb_idx'),
        ),
    ]
