# Generated by Django 5.2.4 on 2025-08-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auditsource_is_active_gaptype_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('validation_request', 'Demande de validation'), ('validation_approved', 'Validation approuvée'), ('validation_rejected', 'Validation rejetée'), ('validation_completed', 'Validation effectuée'), ('gap_retained', 'Écart retenu'), ('gap_rejected', 'Écart non retenu'), ('gap_created', 'Écart créé'), ('gap_modified', 'Écart modifié'), ('gap_deleted', 'Écart supprimé'), ('gap_status_changed', 'Statut modifié'), ('declaration_involved', 'Impliqué dans une déclaration')], max_length=20, verbose_name='Type de notification'),
        ),
    ]
