# Generated by Django 5.2.4 on 2025-08-14 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_declaration_involved_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='gap_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.gapreport', verbose_name='Déclaration concernée'),
        ),
    ]
